"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, environ #환경변수

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 보안코드
env = environ.Env(
    DEBUG=(bool, False),  # DEBUG 환경변수 설정
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env')) # .env 파일에서 환경변수 읽기

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]  # 모든 호스트 허용, 실제 배포시에는 특정 도메인으로 제한하는 것이 좋음

# Application definition
CUSTOM_APPS = [
    'todo',
    "interaction",
]

THIRD_PARTY_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',    
    'django_extensions',
]

INSTALLED_APPS = CUSTOM_APPS + THIRD_PARTY_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'KO-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATICFILES_DIRS = [
    BASE_DIR / "static",
]

REST_FRAMEWORK = {
    # 페이지네이션 클래서 : 커스텀 지정
    "DEFAULT_PAGINATION_CLASS": "todo.pagination.CustomPageNumberPagination",
    "PAGE_SIZE": 3, 
    
     # 인증 클래스 : 사용자의 로그인 여부를 판단하는 방법 지정
    # JWT 토큰 기반 인증
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication", # 로그인된 사용자만 접근 허용
    ],
    
    
    # 권한 클래스 : 인증된 사용자만 접근 가능하도록 설정
    "DEFAULT_PERMISSION_CLASSES":[
        "rest_framework.permissions.IsAuthenticated",
    ],
}    

LOGIN_REDIRECT_URL = '/todo/list/',    
LOGIN_URL = '/api-auth/login/'  # 로그인 페이지 URL

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 미디어 파일 저장 경로 설정

# # Fly 배포용 ALLOWED_HOSTS 설정
# APP_NAME = os.environ.get("FLY_APP_NAME")
# #ALLOWED_HOSTS = [f"{APP_NAME}.fly.dev", "localhost", "127.0.0.1"]
# ALLOWED_HOSTS = [f"{APP_NAME}.fly.dev", "localhost", "127.0.0.1","todolist-drf-wandering-snow-5082.fly.dev",]

# CSRF_TRUSTED_ORIGINS = [
#     f"https://{APP_NAME}.fly.dev/",
#     "https://todolist-drf-wandering-snow-5082.fly.dev"  # ← 본인 앱 도메인
# ]
# 뵨인의 도메인으로 수정

# 정적파일 경로
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')